@startuml

mainframe SD **UC01** 

'UC01: Como desenvolvedor, desejo abrir a aba no menu lateral do VS Code, trazendo informações pertinentes à extensão.

actor       Desenvolvedor                     as Dev
participant "Visual Studio Code"              as VSCode
participant "Extension Orchestration Service" as ExtensionOrchestrationService
participant "Project Configuration Service"   as ProjectConfigurationService
participant "Project Configuration"           as ProjectConfiguration
participant "File Coverage Service"           as FileCoverageService
participant "File Coverage"                   as FileCoverage
participant "Configuration View"              as ConfigurationView
participant "Coverage View"                   as CoverageView
participant "Uncovered Lines Tree"            as UncoveredLinesTree

Dev -> VSCode: changeToCoveringTab()
activate Dev
activate VSCode

VSCode -> VSCode: changeWebView()
VSCode -> ExtensionOrchestrationService: initViewData()
activate ExtensionOrchestrationService


ExtensionOrchestrationService -> ProjectConfigurationService: getConfigurationData()
activate ProjectConfigurationService

opt caso seja a primeira inicialização
  create ProjectConfiguration
  ProjectConfigurationService --> ProjectConfiguration
end

ExtensionOrchestrationService <-- ProjectConfigurationService: configuration data
deactivate ProjectConfigurationService

ExtensionOrchestrationService -> FileCoverageService: getCoverageData()
activate FileCoverageService

opt caso seja a primeira inicialização
  create FileCoverage
  FileCoverageService --> FileCoverage
end

ExtensionOrchestrationService <-- FileCoverageService: coverage data
deactivate FileCoverageService

opt caso seja a primeira inicialização
  create ConfigurationView
  ExtensionOrchestrationService --> ConfigurationView
  create CoverageView
  ExtensionOrchestrationService --> CoverageView
  create UncoveredLinesTree
  ExtensionOrchestrationService --> UncoveredLinesTree
end


ExtensionOrchestrationService -> ConfigurationView: createView()
activate ConfigurationView
ExtensionOrchestrationService <-- ConfigurationView: screenFragmentReference
deactivate ConfigurationView

ExtensionOrchestrationService -> CoverageView: createView()
activate CoverageView
ExtensionOrchestrationService <-- CoverageView: screenFragmentReference
deactivate CoverageView

ExtensionOrchestrationService -> UncoveredLinesTree: createView()
activate UncoveredLinesTree
ExtensionOrchestrationService <-- UncoveredLinesTree: screenFragmentReference
deactivate UncoveredLinesTree

VSCode <-- ExtensionOrchestrationService: returnCalculatedView
deactivate ExtensionOrchestrationService

Dev <-- VSCode: Renderiza os dados de acordo as configurações
deactivate VSCode
deactivate Dev

@enduml
