@startuml

mainframe SD **UC02** 

'UC02: Como desenvolvedor, desejo alternar a visualização do status de cada linha no editor.

actor       Desenvolvedor                     as Dev
participant "Configuration View"              as ConfigurationView
participant "Extension Configuration Service" as ExtensionConfigurationService
participant "Extension Configuration Data"    as ExtensionConfigurationData
participant "Extension Orchestration Service" as ExtensionOrchestrationService
participant "Coverage Service"                as CoverageService
participant "Visual Studio Code"              as VSCode

Dev -> ConfigurationView: toggleLineStatusVisibility()
activate Dev
activate ConfigurationView

ConfigurationView -> ExtensionConfigurationService: toggleLineStatusVisibility()
activate ExtensionConfigurationService

ExtensionConfigurationService -> ExtensionConfigurationData: updateConfigurationData()
activate ExtensionConfigurationData

ExtensionConfigurationService <-- ExtensionConfigurationData: newConfigurationData: ConfigurationData
deactivate ExtensionConfigurationData

ExtensionConfigurationService -> ExtensionOrchestrationService: emitNewConfigurationData(newConfigurationData: ConfigurationData)
activate ExtensionOrchestrationService

alt está exibindo o status de cada linha no editor

  ExtensionOrchestrationService -> CoverageService: changeEditorVisibility(false)
  activate CoverageService
else não está exibindo o status de cada linha no editor
  ExtensionOrchestrationService -> CoverageService: changeEditorVisibility(true)
end

CoverageService -> VSCode: changeEditoreDecoration()
activate VSCode

CoverageService <-- VSCode: update editor decoration
deactivate VSCode

ExtensionOrchestrationService <-- CoverageService
deactivate CoverageService

ExtensionConfigurationService <-- ExtensionOrchestrationService
deactivate ExtensionOrchestrationService

ConfigurationView <-- ExtensionConfigurationService
deactivate ExtensionConfigurationService

alt está exibindo o status de cada linha no editor

  Dev <-- ConfigurationView: Remove a visualização o status de cada linha no editor

else não está exibindo o status de cada linha no editor

  Dev <-- ConfigurationView: Exibe o status de cada linha no editor
  
  deactivate Dev
  deactivate ConfigurationView

end
@enduml
