@startuml

mainframe SSD **UC03** 

'UC03: Como desenvolvedor, desejo alterar a visualização da porcentagem de cobertura entre total e em relação ao arquivo aberto.

actor       Desenvolvedor as Dev
participant "Configuration View" as ConfigurationView
participant "Extension Configuration Service" as ExtensionConfigurationService
participant "Extension Configuration Data" as ExtensionConfigurationData
participant "Extension Orchestration Service" as ExtensionOrchestrationService
participant "Coverage Service" as CoverageService
participant "Coverage Data" as CoverageData
participant "Coverage View" as CoverageView
participant "Visual Studio Code" as VSCode

Dev -> ConfigurationView: toggleCoveragePercentageMode()

activate Dev
activate ConfigurationView

ConfigurationView -> ExtensionConfigurationService: toggleCoveragePercentageMode()
activate ExtensionConfigurationService

ExtensionConfigurationService -> ExtensionConfigurationData: updateConfigurationData()
activate ExtensionConfigurationData

ExtensionConfigurationService <-- ExtensionConfigurationData: newConfigurationData: ConfigurationData
deactivate ExtensionConfigurationData

ExtensionConfigurationService -> ExtensionOrchestrationService: emitNewConfigurationData(newConfigurationData: ConfigurationData)
activate ExtensionOrchestrationService

alt deve exibir a porcentagem para todos os arquivos

  ExtensionOrchestrationService -> VSCode: cancelEditorFocusChangeObeservation()
  activate VSCode
  ExtensionOrchestrationService <-- VSCode
  deactivate VSCode

  ExtensionOrchestrationService -> CoverageService: calculateCoverage()
  activate CoverageService

  CoverageService -> CoverageData: updateCoverageData()
  activate CoverageData

  CoverageService <-- CoverageData: newCoverageData: CoverageData
  deactivate CoverageData

  CoverageService -> CoverageView: emitNewCoverageData(newCoverageData: CoverageData)
  activate CoverageView

  CoverageService <-- CoverageView
  deactivate CoverageView

  ExtensionOrchestrationService <-- CoverageService
  deactivate CoverageService

else deve exibir a porcentagem somente para o arquivo em foco no editor

  ExtensionOrchestrationService -> VSCode: observeEditorFocusChange()
  activate VSCode
  
  par
    loop enquanto não trocar a configuração
      VSCode -> VSCode: focusChange()
      ExtensionOrchestrationService <-- VSCode: new file on focus
      deactivate VSCode

      ExtensionOrchestrationService -> CoverageService: calculateCoverage()
      activate CoverageService

      note right
        Ao calcular a cobertura leva em consideração a configuração
        e a partir disso mostra somente as linhas desejadas ou todas
      end note

      CoverageService -> CoverageData: updateCoverageData()
      activate CoverageData

      CoverageService <-- CoverageData: newCoverageData: CoverageData
      deactivate CoverageData

      CoverageService -> CoverageView: emitNewCoverageData(newCoverageData: CoverageData)
      activate CoverageView

      CoverageService <-- CoverageView
      deactivate CoverageView

      ExtensionOrchestrationService <-- CoverageService
      deactivate CoverageService
    end
  end
end


ExtensionConfigurationService <-- ExtensionOrchestrationService
deactivate ExtensionOrchestrationService

ConfigurationView <-- ExtensionConfigurationService
deactivate ExtensionConfigurationService

alt está exibindo a porcentagem para todos os arquivos

  Dev <-- ConfigurationView: Recalcular porcentagem de cobertura somente para o arquivo em foco no editor

else está exibindo a porcentagem somente para o arquivo em foco no editor

  Dev <-- ConfigurationView: Recalcular porcentagem de cobertura para todos arquivos do projeto

end

@enduml
