@startuml

mainframe SD **UC05** 

'UC05: Como desenvolvedor, desejo solicitar a geração do arquivo de configuração.

actor       Desenvolvedor                   as Dev
participant "Visual Studio Code"            as VSCode
participant "Project Configuration Service" as ProjectConfigurationService

Dev -> ProjectConfigurationService: requireConfigFileGeneration()
activate Dev
activate ProjectConfigurationService

alt o arquivo já existir

  ProjectConfigurationService -> VSCode: openConfirmationDialog()
  activate VSCode

  Dev <- VSCode: Caixa de dialogo para confirmar sobrescrita
  
  alt confirmar sobrescrita

    Dev --> VSCode: confirmation
    ProjectConfigurationService <-- VSCode: confirmation

    ProjectConfigurationService -> VSCode: requestFileGeneration()
    ProjectConfigurationService <-- VSCode
    
    Dev <-- ProjectConfigurationService: Criar o arquivo de template na raiz 

  else não confirma sobrescrita

    Dev --> VSCode: reject
    ProjectConfigurationService <-- VSCode: reject
    
    ProjectConfigurationService -> VSCode: redirectEditorTo(configFilePath: string)
    ProjectConfigurationService <-- VSCode
    deactivate VSCode

    Dev <-- ProjectConfigurationService: Redireciona para o arquivo existente
  
  end

else o arquivo não exite

  ProjectConfigurationService -> VSCode: requestFileGeneration()
  activate VSCode
  ProjectConfigurationService <-- VSCode
  deactivate VSCode
  
  Dev <-- ProjectConfigurationService: Criar o arquivo de template na raiz 
  deactivate Dev
  deactivate ProjectConfigurationService
  
end

@enduml
