@startuml

mainframe SD **UC06** 

'UC06: Como desenvolvedor, desejo criar na raiz do projeto o arquivo de configuração.

actor       Desenvolvedor                     as Dev
participant "Visual Studio Code"              as VSCode
participant "Project Configuration Service"   as ProjectConfigurationService
participant "Project Configuration"           as ProjectConfiguration
participant "Extension Orchestration Service" as ExtensionOrchestrationService
participant "Configuration View"              as ConfigurationView
participant "Coverage View"                   as CoverageView
participant "Uncovered Lines Tree"            as UncoveredLinesTree

Dev -> VSCode: cria na raiz do projeto um arquivo de configuração
activate Dev
activate VSCode

VSCode -> ProjectConfigurationService: emitNewFileCreated()
activate ProjectConfigurationService

ProjectConfigurationService -> ProjectConfiguration: createNewConfiguration()
activate ProjectConfiguration
ProjectConfigurationService <-- ProjectConfiguration: newProjectConfiguration: ProjectConfiguration
deactivate ProjectConfiguration

ProjectConfigurationService -> ExtensionOrchestrationService: emitNewFileCreated()
deactivate ProjectConfigurationService
activate ExtensionOrchestrationService

ExtensionOrchestrationService -> ConfigurationView: createView()
activate ConfigurationView
ExtensionOrchestrationService <-- ConfigurationView: screenFragmentReference
deactivate ConfigurationView

ExtensionOrchestrationService -> CoverageView: createView()
activate CoverageView
ExtensionOrchestrationService <-- CoverageView: screenFragmentReference
deactivate CoverageView

ExtensionOrchestrationService -> UncoveredLinesTree: createView()
activate UncoveredLinesTree
ExtensionOrchestrationService <-- UncoveredLinesTree: screenFragmentReference
deactivate UncoveredLinesTree

VSCode <-- ExtensionOrchestrationService: returnCalculatedView
deactivate ExtensionOrchestrationService

Dev <-- VSCode: Renderiza os dados de acordo as configurações
deactivate VSCode
deactivate ExtensionOrchestrationService
deactivate Dev

@enduml
