name: Pre-publish

on: [push, pull_request]

jobs:
  lint:
    uses: ./.github/workflows/lint.yaml
  tests:
    uses: ./.github/workflows/tests.yaml
  upload-package:
    uses: ./.github/workflows/upload-package.yaml
