name: Deploy Extension

on:
  push:
    tags:
      - v*

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Codigo
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      
      - name: Install dependencies
        run: npm ci
      
      - name: Lint
        run: npm run lint

  tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Codigo
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run tests with coverage report
        run: npm run test:cov

      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: |
            **/coverage-report/lcov-report

      - name: Code Coverage Summary Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: | 
            coverage-report/clover.xml

  upload-package:
    runs-on: ubuntu-latest
    needs: tests
    defaults:
      run:
        working-directory: ./Codigo
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      
      - name: Install dependencies
        run: npm ci
      
      - name: Generate vsix file
        run:  npm run vsce package  
      
      - name: Archive vsix artifact
        uses: actions/upload-artifact@v3
        with:
          path: |
            **/covering-*.vsix

  deploy:
    runs-on: ubuntu-latest
    needs: tests
    environment: production
    defaults:
      run:
        working-directory: ./Codigo
    env:
      VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - run: npm ci
      - run: npm run vsce:ci "$VSCE_TOKEN"
